name: Deploy Garden

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  
  deploy:
    env:
      AWS_REGION: eu-west-2
      CLUSTER_NAME: eks-lab-cluster
      HELM_RELEASE: garden
      NAMESPACE: garden
      CHART: oci://registry-1.docker.io/johnwalker333/garden
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.CLUSTER_NAME }}

      - name: Install Helm
        uses: azure/setup-helm@v4.3.0

      - name: Deploy Helm chart to EKS
        run: |
          helm upgrade --install ${{ env.HELM_RELEASE }} ${{ env.CHART }} \
            --namespace ${{ env.NAMESPACE }} --create-namespace \
            -f values.yaml

        
  